### ISSUE TITLE
Integrate ExternalSecrets with Vault

### ISSUE THREAD

**Issue by dwinchell** [ploigos/infra-ops#11]
Success Criteria:
* When I manually add a secret to vault and then create an ExternalSecret CR, the ExternalSecrets operator creates a Secret
* The Secret has the same value I entered in Vault
* All prerequisites to the above actions are either fully automated (preferable) or documented in the infra-ops README

Out of Scope:
* Using an ExternalSecret in the github runner helm chart

**Comment by aarongreen85** [comment]
When we started using the external secrets operator, we ran into an issue because we hadn't yet installed an operator config instance. In thinking about how we want to install this using argo anyway, we decided to drop the operator and install using the default helm chart. Once installed and resources were up, we added a secret store using a vault token and an external secret referencing that secret store. That then created the openshift secret.

```
$ helm install external-secrets external-secrets/external-secrets -n external-secrets --create-namespace --set installCRDs=true
NAME: external-secrets
LAST DEPLOYED: Thu Jun 16 10:55:53 2022
NAMESPACE: external-secrets
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
external-secrets has been deployed successfully!

In order to begin using ExternalSecrets, you will need to set up a SecretStore
or ClusterSecretStore resource (for example, by creating a 'vault' SecretStore).

More information on the different types of SecretStores and how to configure them
can be found in our Github: https://github.com/external-secrets/external-secrets
$ oc apply -f es-example-store.yaml 
secretstore.external-secrets.io/vault-backend created
$ oc get ss
NAME            AGE   STATUS
vault-backend   3s    Valid
$ oc apply -f es-example-value.yaml 
externalsecret.external-secrets.io/vault-example created
$ oc get es
NAME            STORE           REFRESH INTERVAL   STATUS
vault-example   vault-backend   15s                SecretSynced
$ oc get secret/example-value
NAME            TYPE     DATA   AGE
example-value   Opaque   1      15s
```
